### ISSUE TITLE
Features icons should link to their respective PCGamingWiki search queries

### ISSUE THREAD

**Issue by connorshea** [PCGamingWiki/pcgwext#1]
e.g. the "Full controller support" icon would [link here](http://pcgamingwiki.com/w/index.php?title=Special:SearchByProperty&offset=0&limit=500&property=Full+controller+support&value=true). Maybe add an additional qualifier that filters it to only "Full controller support" and "GOG.com games" so it doesn't link Steam games, for example? 

[SteamDB does this with their features icons](https://steamdb.info/app/420/), so I figure it'd be sensible to ~~steal~~ borrow their idea.

**Comment by Aemony** [comment]
This browser extension was retired back in 2019, and users are recommended to switch to an alternative. Please see [PCGamingWiki](https://www.pcgamingwiki.com/wiki/PCGamingWiki:Extension) for more information.
