### ISSUE TITLE
Broken PCGW links

### ISSUE THREAD

**Issue by Keith94** [PCGamingWiki/pcgwext#3]
The PCGW link on the [Planescape: Torment](http://www.gog.com/game/planescape_torment) page seems to be broken, with it saying the page doesn't exist.

I'm running Nightly on Windows 8.

**Comment by connorshea** [comment]
This has been fixed on my end, although I have no idea why.

**Comment by connorshea** [comment]
This was a problem with the MediaWiki API that's since been fixed to my knowledge. Please comment again if you see any problems.
