### ISSUE TITLE
e10s compatibility issue

### ISSUE THREAD

**Issue by Keith94** [PCGamingWiki/pcgwext#4]
When e10s is enabled in Nightly, visiting a gog.com page will crash the tabs.

In the browser console it shows `NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIProperties.get] FileUtils.jsm:63:0`

Some info: https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox

**Comment by ghost** [comment]
Thanks, I'll look into it.

**Comment by mirh** [comment]
_Soeb can't into deadlines_

**Comment by Keith94** [comment]
I think the issue fixed itself, no more crashing.
