### ISSUE TITLE
Add Steam support

### ISSUE THREAD

**Issue by connorshea** [PCGamingWiki/pcgwext#5]
Enhanced Steam has [dropped support for Firefox](https://steamcommunity.com/groups/enhancedsteam#announcements/detail/234525530731921313), so it's probably a good idea to add PCGW links to Steam pages via our extension now. We'll have to take a look at avoiding conflicts with users of the ES or SteamDB extensions, is there any way to detect other extensions present in a browser? If not, we can probably just use JavaScript to check for the class/id names that they add for PCGW buttons in their respective extensions.

I'd prefer this added sooner rather than later to take advantage of the whole ES thing.

**Comment by ghost** [comment]
I'll see about assigning some time to this.

While on it, we should consider adding a couple more features, the way we do on GOG.

**Comment by Keith94** [comment]
Enhanced Steam for Firefox is still [receiving updates](https://github.com/jshackles/Enhanced_Steam_Firefox/commits/master) btw.

**Comment by Aemony** [comment]
This browser extension was retired back in 2019, and users are recommended to switch to an alternative. Please see [PCGamingWiki](https://www.pcgamingwiki.com/wiki/PCGamingWiki:Extension) for more information.
