### ISSUE TITLE
Missing Wikipedia links

### ISSUE THREAD

**Issue by DrCat7** [PCGamingWiki/pcgwext#7]
OS: Windows 8.1
Browsers: Chrome 44.0.2403.130 m, Firefox 39.0.3

The "Wikipedia" button is missing on some games that do possess a Wikipedia page.
This has happened on The Wolf Among Us and all TellTale The Walking Dead games.

**Comment by ghost** [comment]
This is not a bug. The pages on PCGW lack the correct tags and therefore the extension is unable to get the data.

**Comment by ghost** [comment]
For reference, these are the required additions: http://pcgamingwiki.com/w/index.php?title=The_Wolf_Among_Us&diff=183504&oldid=180750
